name: S3_Neural_Networks
channels:
  - conda-forge
  - defaults
dependencies:
  - absl-py=2.1.0=py312haa95532_0
  - asttokens=3.0.0=pyhd8ed1ab_1
  - astunparse=1.6.3=py_0
  - blas=1.0=mkl
  - bottleneck=1.4.2=py312h540bb41_1
  - brotlicffi=1.1.0.0=py312h885b0b7_0
  - bzip2=1.0.8=h2bbff1b_6
  - c-ares=1.34.5=h731ff69_0
  - ca-certificates=2025.12.2=haa95532_0
  - certifi=2025.11.12=pyhd8ed1ab_0
  - cffi=2.0.0=py312h02ab6af_1
  - charset-normalizer=3.4.4=py312haa95532_0
  - click=8.2.1=py312haa95532_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.3=pyhe01879c_0
  - contourpy=1.3.1=py312h214f63a_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - debugpy=1.8.16=py312h885b0b7_1
  - decorator=5.2.1=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - expat=2.7.3=h9214b88_0
  - flatbuffers=24.3.25=h21716d4_0
  - fonttools=4.60.1=py312h02ab6af_0
  - freetype=2.13.3=h0620614_0
  - gast=0.6.0=pyhd3eb1b0_0
  - giflib=5.2.2=h7edc060_0
  - google-pasta=0.2.0=pyhd3eb1b0_0
  - grpcio=1.71.0=py312hbb1fe6b_0
  - h5py=3.14.0=py312h6fc9867_0
  - hdf5=1.14.5=ha36df97_2
  - icc_rt=2022.1.0=h6049295_2
  - icu=73.1=h6c2663c_0
  - idna=3.11=py312haa95532_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - intel-openmp=2025.0.0=haa95532_1164
  - ipykernel=7.1.0=pyh6dadd2b_0
  - ipython=9.7.0=pyhe2676ad_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - joblib=1.5.2=py312haa95532_0
  - jpeg=9f=ha349fce_0
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.9.1=pyh6dadd2b_0
  - keras=3.11.2=py312h51baaa3_0
  - kiwisolver=1.4.8=py312h5da7b33_0
  - krb5=1.21.3=hdf4eb48_0
  - lcms2=2.16=hb4a4139_0
  - lerc=3.0=hd77b12b_0
  - libabseil=20250127.0=cxx17_h52369b4_0
  - libcurl=8.16.0=h97e0424_0
  - libdeflate=1.17=h2bbff1b_1
  - libffi=3.4.4=hd77b12b_1
  - libgrpc=1.71.0=hf4237ab_0
  - libpng=1.6.50=h46444df_0
  - libprotobuf=5.29.3=h65a231f_1
  - libre2-11=2024.07.02=h5da7b33_0
  - libsodium=1.0.20=hc70643c_0
  - libssh2=1.11.1=h2addb87_0
  - libtiff=4.5.1=hd77b12b_0
  - libwebp-base=1.3.2=h3d04722_1
  - libzlib=1.3.1=h02ab6af_0
  - lz4-c=1.9.4=h2bbff1b_1
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - markdown=3.8=py312haa95532_0
  - markdown-it-py=2.2.0=py312haa95532_1
  - markupsafe=3.0.2=py312h827c3e9_0
  - matplotlib-base=3.10.6=py312h43afe63_1
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - mdurl=0.1.2=py312haa95532_0
  - mkl=2025.0.0=h5da7b33_930
  - mkl-service=2.5.2=py312h0b37514_0
  - mkl_fft=2.1.1=py312h300f80d_0
  - mkl_random=1.3.0=py312ha5e6156_0
  - ml_dtypes=0.5.1=py312h094160a_0
  - mpi=1.0=msmpi
  - mpi4py=4.0.3=py312h827c3e9_0
  - msmpi=10.1.1=had4844c_0
  - msys2-conda-epoch=20160418=1
  - namex=0.1.0=py312haa95532_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - nltk=3.9.2=py312ha55a155_0
  - numexpr=2.14.1=py312h7660c64_0
  - numpy=2.1.3=py312h12f7302_3
  - numpy-base=2.1.3=py312he4e2855_3
  - openjpeg=2.5.2=hae555c5_0
  - openssl=3.6.0=h725018a_0
  - opt_einsum=3.3.0=pyhd3eb1b0_1
  - optree=0.14.1=py312h214f63a_0
  - packaging=25.0=py312haa95532_1
  - pandas=2.3.3=py312h42c1672_1
  - parso=0.8.5=pyhcf101f3_0
  - pillow=11.1.0=py312h096bfcc_0
  - pip=25.2=pyhc872135_1
  - platformdirs=4.5.0=pyhcf101f3_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - protobuf=5.29.3=py312h5da7b33_0
  - psutil=7.0.0=py312h02ab6af_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pycparser=2.23=py312haa95532_0
  - pygments=2.19.2=py312haa95532_0
  - pyparsing=3.2.0=py312haa95532_0
  - pysocks=1.7.1=py312haa95532_1
  - python=3.12.12=h716150d_1
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-flatbuffers=24.3.25=py312haa95532_0
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - pytz=2025.2=py312haa95532_0
  - pywin32=311=py312h885b0b7_0
  - pyzmq=27.1.0=py312h7149c55_1
  - re2=2024.07.02=h214f63a_0
  - regex=2025.9.1=py312h02ab6af_0
  - requests=2.32.5=py312haa95532_1
  - rich=14.2.0=py312haa95532_0
  - scikit-learn=1.7.1=py312h3fbe716_0
  - scipy=1.16.3=py312hbd6d557_0
  - seaborn=0.13.2=py312haa95532_3
  - setuptools=80.9.0=py312haa95532_0
  - six=1.17.0=py312haa95532_0
  - snappy=1.2.1=hcdb6601_0
  - sqlite=3.51.0=hda9a48d_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tbb=2022.0.0=h214f63a_0
  - tbb-devel=2022.0.0=h214f63a_0
  - tensorboard=2.19.0=py312haa95532_0
  - tensorboard-data-server=0.7.0=py312haa95532_1
  - tensorflow=2.19.1=cpu_py312h6605a60_0
  - tensorflow-base=2.19.1=cpu_py312h4cf5749_0
  - termcolor=3.2.0=py312haa95532_0
  - threadpoolctl=3.5.0=py312h4442805_1
  - tk=8.6.15=hf199647_0
  - tornado=6.5.1=py312h827c3e9_0
  - tqdm=4.67.1=py312h4442805_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing-extensions=4.15.0=py312haa95532_0
  - typing_extensions=4.15.0=py312haa95532_0
  - tzdata=2025b=h04d1e81_0
  - ucrt=10.0.22621.0=haa95532_0
  - urllib3=2.5.0=py312haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - werkzeug=3.1.3=py312haa95532_0
  - wheel=0.45.1=py312haa95532_0
  - win_inet_pton=1.1.0=py312haa95532_1
  - wrapt=1.17.0=py312h827c3e9_0
  - xz=5.6.4=h4754444_1
  - zeromq=4.3.5=h5bddc39_9
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.3.1=h02ab6af_0
  - zstd=1.5.7=h56299aa_0
  - pip:
      - anyascii==0.3.3
      - contractions==0.1.73
      - pyahocorasick==2.2.0
      - scikeras==0.13.0
      - textsearch==0.0.24
prefix: C:\Users\wsidn\.conda\envs\S3_Neural_Networks
